"""feeds

Revision ID: 423542de4400
Revises: 59d84cef0d63
Create Date: 2014-07-29 23:30:31.000831

"""

# revision identifiers, used by Alembic.
revision = '423542de4400'
down_revision = '59d84cef0d63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_table('subscribe',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('type', sa.String(length=32), nullable=True),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('feed_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_subscribe_active'), 'subscribe', ['active'], unique=False)
    op.create_index(op.f('ix_subscribe_name'), 'subscribe', ['name'], unique=False)
    op.create_index(op.f('ix_subscribe_parent_id'), 'subscribe', ['parent_id'], unique=False)
    op.create_index(op.f('ix_subscribe_type'), 'subscribe', ['type'], unique=False)

    op.create_table('image',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('extension', sa.String(length=255), nullable=True),
        sa.Column('path', sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('feed',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=4096), nullable=True),
        sa.Column('channel_url', sa.String(length=4096), nullable=True),
        sa.Column('icon_image_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['icon_image_id'], ['image.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_active'), 'feed', ['active'], unique=False)
    op.create_index(op.f('ix_feed_channel_url'), 'feed', ['channel_url'], unique=False)
    op.create_index(op.f('ix_feed_created'), 'feed', ['created'], unique=False)
    op.create_index(op.f('ix_feed_last_update'), 'feed', ['last_update'], unique=False)

    op.create_table('article',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=2048), nullable=True),
        sa.Column('article_url', sa.String(length=4096), nullable=True),
        sa.Column('preview_image_id', sa.Integer(), nullable=True),
        sa.Column('feed_id', sa.Integer(), nullable=True),
        sa.Column('preview_text', sa.Text(), nullable=True),
        sa.Column('full_text', sa.Text(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('published', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['preview_image_id'], ['image.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_article_active'), 'article', ['active'], unique=False)
    op.create_index(op.f('ix_article_article_url'), 'article', ['article_url'], unique=False)
    op.create_index(op.f('ix_article_published'), 'article', ['published'], unique=False)

    op.create_table('article_status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('article_id', sa.Integer(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_article_status_status'), 'article_status', ['status'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), server_default="nextval('users_id_seq'::regclass)", nullable=False),
        sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('hash_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='id')
    )

    op.drop_index(op.f('ix_article_published'), table_name='article')
    op.drop_index(op.f('ix_article_article_url'), table_name='article')
    op.drop_index(op.f('ix_article_active'), table_name='article')

    op.drop_table('article')

    op.drop_index(op.f('ix_feed_last_update'), table_name='feed')
    op.drop_index(op.f('ix_feed_created'), table_name='feed')
    op.drop_index(op.f('ix_feed_channel_url'), table_name='feed')
    op.drop_index(op.f('ix_feed_active'), table_name='feed')

    op.drop_table('feed')

    op.drop_index(op.f('ix_article_status_status'), table_name='article_status')

    op.drop_table('article_status')
    op.drop_table('image')

    op.drop_index(op.f('ix_subscribe_type'), table_name='subscribe')
    op.drop_index(op.f('ix_subscribe_parent_id'), table_name='subscribe')
    op.drop_index(op.f('ix_subscribe_name'), table_name='subscribe')
    op.drop_index(op.f('ix_subscribe_active'), table_name='subscribe')

    op.drop_table('subscribe')
    ### end Alembic commands ###
