"""user_profile

Revision ID: 30d3410b1a3b
Revises: 520afc544eff
Create Date: 2015-03-01 23:07:46.032828

"""

# revision identifiers, used by Alembic.
revision = '30d3410b1a3b'
down_revision = '520afc544eff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('show_tutorial', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'show_tutorial')
    ### end Alembic commands ###
