FROM python:2.7

RUN apt-get update -y && apt-get install -q -y python-psycopg2 libpq-dev libjpeg-dev libxml2-dev libxslt1-dev python-dev libffi-dev nodejs npm nodejs-legacy uwsgi uwsgi-plugin-python xvfb python-pyasn1 python-pyasn1-modules

RUN npm install -g less

RUN npm install -g uglify uglifycss

ADD "./docker/wkhtmltopdf-xvfb.sh" "/app/docker/wkhtmltopdf-xvfb.sh"
RUN cd /tmp && \
 	wget -q https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz && \
 	tar -xf "./wkhtmltox-0.12.4_linux-generic-amd64.tar.xz" && \
 	mv ./wkhtmltox /opt/ && \
 	chmod a+x /opt/wkhtmltox/bin/wkhtmltoimage && \
 	chmod a+x /opt/wkhtmltox/bin/wkhtmltopdf && \
 	cp /app/docker/wkhtmltopdf-xvfb.sh /usr/bin/wkhtmltopdf-xvfb.sh && \
 	chmod a+x /usr/bin/wkhtmltopdf-xvfb.sh

WORKDIR /app/

ADD requirements.txt requirements.txt

RUN pip install -r requirements.txt

# https://stackoverflow.com/questions/15608236/eclipse-and-google-app-engine-importerror-no-module-named-sysconfigdata-nd-u
RUN ln -s /usr/lib/python2.7/plat-*/_sysconfigdata_nd.py /usr/lib/python2.7/